name = "InfinitaryLogic"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["InfinitaryLogic"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.27.0"

[[require]]
name = "LeanArchitect"
git = "https://github.com/cameronfreer/LeanArchitect.git"
rev = "e14a867"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "InfinitaryLogic"
