/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import InfinitaryLogic.Methods.WellOrdering.Undefinability
import InfinitaryLogic.Methods.SymbSublangExpansion

/-!
# Removing symbol countability (issue #12, the sublanguage wrapper)

The step-5/6 theorems assumed `[Countable (Σ l, L.Relations l)]` for the fair enumeration.
This wrapper removes it by the two-sorted symbol-generated sublanguage
(`symbSublang φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn)` — both sorts countable,
**proved** from the sentence's own symbol supply, with `lt` inserted so the distinguished
relation survives the restriction):

* the well-ordered-chains hypothesis transfers to the sublanguage along reducts;
* the sublanguage endpoint produces the model and rational map;
* `expandSymbStructureBase` expands the model back to `L`, preserving the root
  (`realize_restrictSymbols_expandSymbStructureBase`) and the relation (`dif_pos`).

`[L.IsRelational]` remains — it is consumed by the quotient term model, and its removal is
the separate arbitrary-function-language graph translation, not this wrapper.
-/

namespace FirstOrder.Language

open FirstOrder Structure

variable {L : Language.{0, 0}}

/-- A two-sorted sublanguage of a relational language is relational. -/
theorem symbSublang_isRelational [L.IsRelational] (F : Set (Σ n, L.Functions n))
    (R : Set (Σ n, L.Relations n)) : (symbSublang (L := L) F R).IsRelational :=
  fun n => ⟨fun f => (‹L.IsRelational› n).false f.1⟩

/-- **Step-5 endpoint, no symbol countability** (relational): the countable-relational-core
hypothesis of `exists_model_relPreserving_relational` removed via the two-sorted sublanguage
generated by the sentence's own symbols together with `lt`. -/
theorem exists_model_relPreserving_isRelational [L.IsRelational]
    (φ : L.Sentenceω) (lt : L.Relations 2) (h : HasWellOrderedChains φ lt) :
    ∃ (M : Type) (_ : L.Structure M) (_ : Nonempty M) (f : ℚ → M),
      Sentenceω.Realize φ M ∧ RelPreserving lt f := by
  classical
  haveI : (symbSublang (L := L) φ.functionsIn
      (insert ⟨2, lt⟩ φ.relationsIn)).IsRelational := symbSublang_isRelational _ _
  haveI : Countable (Σ n, (symbSublang (L := L) φ.functionsIn
      (insert ⟨2, lt⟩ φ.relationsIn)).Functions n) :=
    symbSublang_fun_countable φ.functionsIn_countable _
  haveI : Countable (Σ l, (symbSublang (L := L) φ.functionsIn
      (insert ⟨2, lt⟩ φ.relationsIn)).Relations l) :=
    symbSublang_rel_countable _ (φ.relationsIn_countable.insert _)
  -- the restricted root and the surviving distinguished relation
  have hchains₀ : HasWellOrderedChains
      (φ.restrictSymbols (subset_refl _) (Set.subset_insert _ _))
      (⟨lt, Set.mem_insert _ _⟩ : (symbSublang (L := L) φ.functionsIn
        (insert ⟨2, lt⟩ φ.relationsIn)).Relations 2) := by
    intro α hα
    obtain ⟨M, instM, ne, hreal, w, hchain⟩ := h α hα
    letI instM₀ := (symbSublangIncl φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn)).reduct M
    haveI : (symbSublangIncl φ.functionsIn
        (insert ⟨2, lt⟩ φ.relationsIn)).IsExpansionOn M := LHom.isExpansionOn_reduct _ _
    refine ⟨M, instM₀, ne, ?_, w, fun x y hxy => hchain x y hxy⟩
    have hmap := BoundedFormulaω.realize_mapLanguage
      (symbSublangIncl φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn))
      (φ.restrictSymbols (subset_refl _) (Set.subset_insert _ _))
      (Empty.elim : Empty → M) Fin.elim0
    rw [BoundedFormulaω.mapLanguage_restrictSymbols] at hmap
    exact hmap.mp hreal
  obtain ⟨N, instN₀, neN, f, hreal₀, hf₀⟩ :=
    exists_model_relPreserving_relational _ _ hchains₀
  letI := instN₀
  haveI := neN
  letI instN : L.Structure N :=
    expandSymbStructureBase φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn)
  haveI : (symbSublangIncl φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn)).IsExpansionOn N := by
    have hred := reduct_expandSymbStructureBase (L := L) φ.functionsIn
      (insert ⟨2, lt⟩ φ.relationsIn) (M := N)
    rw [← hred]
    exact LHom.isExpansionOn_reduct _ _
  refine ⟨N, instN, neN, f, ?_, fun q r hqr => ?_⟩
  · exact (realize_restrictSymbols_expandSymbStructureBase _ _ φ (subset_refl _)
      (Set.subset_insert _ _) Empty.elim Fin.elim0).mp hreal₀
  · have hpres := hf₀ q r hqr
    rw [← LHom.map_onRelation (symbSublangIncl φ.functionsIn
      (insert ⟨2, lt⟩ φ.relationsIn))] at hpres
    exact hpres

/-- **Boundedness, well-founded form, no symbol countability**: layer 2's
`wellFounded_boundedness_relational` through the sublanguage-wrapped endpoint. -/
theorem wellFounded_boundedness_isRelational [L.IsRelational]
    (φ : L.Sentenceω) (lt : L.Relations 2)
    (hwf : ∀ (M : Type) (_ : L.Structure M), Sentenceω.Realize φ M →
      WellFounded fun x y : M => RelMap lt ![x, y]) :
    ∃ α : Ordinal.{0}, α < (Cardinal.aleph 1).ord ∧
      ∀ (M : Type) (_ : L.Structure M), Sentenceω.Realize φ M →
        ¬ ∃ w : α.ToType → M, RelChain lt α w := by
  by_contra hcon
  push Not at hcon
  have hchains : HasWellOrderedChains φ lt := by
    intro α hα
    rcases eq_or_ne α 0 with rfl | hne
    · obtain ⟨M, inst, hreal, w, -⟩ := hcon 1 (by
        have h1 := add_one_lt_omega1 hα
        rwa [zero_add] at h1)
      haveI : Nonempty (Ordinal.ToType 1) := Ordinal.nonempty_toType_iff.mpr one_ne_zero
      exact ⟨M, inst, ⟨w (Classical.arbitrary _)⟩, hreal,
        fun x => isEmptyElim x, fun x => isEmptyElim x⟩
    · obtain ⟨M, inst, hreal, w, hw⟩ := hcon α hα
      haveI : Nonempty α.ToType := Ordinal.nonempty_toType_iff.mpr hne
      exact ⟨M, inst, ⟨w (Classical.arbitrary _)⟩, hreal, w, hw⟩
  obtain ⟨M, instL, -, f, hφreal, hf⟩ := exists_model_relPreserving_isRelational φ lt hchains
  exact not_relPreserving_of_wellFounded (hwf M instL hφreal) f hf

/-- **Boundedness, order-type form, no symbol countability** (Marker Corollary 4.27 at any
relational language). -/
theorem wellOrder_type_boundedness_isRelational [L.IsRelational]
    (φ : L.Sentenceω) (lt : L.Relations 2)
    (hwo : ∀ (M : Type) (_ : L.Structure M), Sentenceω.Realize φ M →
      IsWellOrder M fun x y : M => RelMap lt ![x, y]) :
    ∃ α : Ordinal.{0}, α < (Cardinal.aleph 1).ord ∧
      ∀ (M : Type) (inst : L.Structure M) (hreal : Sentenceω.Realize φ M),
        @Ordinal.type M (fun x y => RelMap lt ![x, y]) (hwo M inst hreal) < α := by
  obtain ⟨α, hα, hnochain⟩ := wellFounded_boundedness_isRelational φ lt
    (fun M inst h => letI := hwo M inst h; IsWellFounded.wf)
  refine ⟨α, hα, fun M inst hreal => ?_⟩
  letI := hwo M inst hreal
  by_contra hle
  rw [not_lt, ← Ordinal.type_toType α] at hle
  obtain ⟨g⟩ := Ordinal.type_le_iff'.mp hle
  exact hnochain M inst hreal ⟨g, fun x y hxy => g.map_rel_iff.mpr hxy⟩

/-- **Undefinability of well-ordering, no symbol countability** (weak form, any relational
language). -/
theorem wellOrdering_undefinable_isRelational {L : Language.{0, 0}} [L.IsRelational]
    (lt : L.Relations 2) :
    ¬ ∃ φ : L.Sentenceω, ∀ (M : Type) (_ : L.Structure M),
        (Sentenceω.Realize φ M ↔ IsWellOrder M fun x y : M => RelMap lt ![x, y]) := by
  rintro ⟨φ, hφ⟩
  obtain ⟨α, hα, hbound⟩ := wellOrder_type_boundedness_isRelational φ lt
    (fun M inst h => (hφ M inst).mp h)
  letI instα : L.Structure α.ToType := ordinalStructure L α
  haveI hwo := ordinalStructure_isWellOrder L α lt
  have hreal : Sentenceω.Realize φ α.ToType := (hφ α.ToType instα).mpr hwo
  have hb := hbound α.ToType instα hreal
  have hiso : (fun x y : α.ToType => RelMap lt ![x, y]) ≃r
      ((· < ·) : α.ToType → α.ToType → Prop) :=
    ⟨_root_.Equiv.refl _, fun {a b} => (ordinalStructure_relMap L α lt a b).symm⟩
  rw [RelIso.ordinalType_congr hiso, Ordinal.type_toType] at hb
  exact absurd hb (lt_irrefl α)

end FirstOrder.Language
