/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import InfinitaryLogic.Lomega1omega.Operations
import Mathlib.Data.Set.Countable

/-!
# The function-generated sublanguage of an `L_{ω₁ω}` formula

Countability plumbing for the Morley–Hanf chain: the local EM tower requires countably many
*function* symbols, but the honest residual statements assume only countably many *relation*
symbols. This file removes the gap: every `L_{ω₁ω}` formula mentions only countably many
function symbols (`functionsIn` + `functionsIn_countable` — formulas are countably-branching
well-founded trees), so the construction can run in the **generated sublanguage** `funSublang F`
(the mentioned functions as a subtype, ALL relations kept — their countability is ambient), and
the formula restricts to it (`restrictFuns`) with `mapLanguage (funSublangIncl F)` as a left
inverse. Downstream (`LocalEMOmegaResidual.lean`) the sublanguage EM model is expanded back to
the full language.

Pure syntax + set-countability; no EM, no local stack, no `Conditional/`.
-/

namespace FirstOrder.Language

variable {L : Language.{0, 0}}

/-! ## Function symbols mentioned by a term / formula -/

/-- The function symbols occurring in a term. -/
def Term.functionsIn {α : Type} : L.Term α → Set (Σ n, L.Functions n)
  | .var _ => ∅
  | .func f ts => insert ⟨_, f⟩ (⋃ i, (ts i).functionsIn)

theorem Term.functionsIn_countable {α : Type} (t : L.Term α) : t.functionsIn.Countable := by
  induction t with
  | var x => exact Set.countable_empty
  | func f ts ih => exact (Set.countable_iUnion ih).insert _

/-- The function symbols occurring in a formula (through all countable connectives). -/
def BoundedFormulaω.functionsIn {α : Type} :
    ∀ {n : ℕ}, L.BoundedFormulaω α n → Set (Σ n, L.Functions n)
  | _, .falsum => ∅
  | _, .equal t u => t.functionsIn ∪ u.functionsIn
  | _, .rel _ ts => ⋃ i, (ts i).functionsIn
  | _, .imp φ ψ => φ.functionsIn ∪ ψ.functionsIn
  | _, .all φ => φ.functionsIn
  | _, .iSup φs => ⋃ i, (φs i).functionsIn
  | _, .iInf φs => ⋃ i, (φs i).functionsIn

theorem BoundedFormulaω.functionsIn_countable {α : Type} {n : ℕ}
    (φ : L.BoundedFormulaω α n) : φ.functionsIn.Countable := by
  induction φ with
  | falsum => exact Set.countable_empty
  | equal t u => exact (t.functionsIn_countable).union (u.functionsIn_countable)
  | rel R ts => exact Set.countable_iUnion fun i => (ts i).functionsIn_countable
  | imp φ ψ ihφ ihψ => exact ihφ.union ihψ
  | all φ ih => exact ih
  | iSup φs ih => exact Set.countable_iUnion ih
  | iInf φs ih => exact Set.countable_iUnion ih

/-! ## The generated sublanguage -/

/-- The sublanguage of `L` generated by a set `F` of function symbols: the functions of `F` (as a
subtype) and **all** of `L`'s relations. Keeping the relations whole means relation-symbol
countability transports from `L` unchanged, and only the function side — the one the local EM
tower needs and the honest residuals do not assume — is cut down to `F`. -/
def funSublang (F : Set (Σ n, L.Functions n)) : Language.{0, 0} where
  Functions n := {f : L.Functions n // ⟨n, f⟩ ∈ F}
  Relations n := L.Relations n

/-- The inclusion of the generated sublanguage. -/
def funSublangIncl (F : Set (Σ n, L.Functions n)) : funSublang (L := L) F →ᴸ L where
  onFunction := fun {_} f => f.1
  onRelation := fun {_} r => r

/-- The generated sublanguage of a countable symbol set has countably many function symbols —
the certificate the local EM tower needs, now provable rather than assumed. -/
theorem funSublang_fun_countable {F : Set (Σ n, L.Functions n)} (hF : F.Countable) :
    Countable (Σ n, (funSublang (L := L) F).Functions n) := by
  haveI := hF.to_subtype
  refine Function.Injective.countable
    (f := fun p : Σ n, (funSublang (L := L) F).Functions n => (⟨⟨p.1, p.2.1⟩, p.2.2⟩ : ↥F)) ?_
  rintro ⟨n, f, hf⟩ ⟨n', f', hf'⟩ h
  simp only [Subtype.mk.injEq] at h
  obtain ⟨rfl, h2⟩ := Sigma.mk.inj_iff.mp h
  cases eq_of_heq h2
  rfl

/-- Relation-symbol countability transports to the generated sublanguage (definitionally the
same relation symbols). -/
theorem funSublang_rel_countable (F : Set (Σ n, L.Functions n))
    [h : Countable (Σ l, L.Relations l)] :
    Countable (Σ l, (funSublang (L := L) F).Relations l) := h

/-! ## Restriction of terms and formulas into the generated sublanguage -/

/-- Restrict a term whose function symbols lie in `F` to the generated sublanguage. -/
def Term.restrictFuns {α : Type} {F : Set (Σ n, L.Functions n)} :
    (t : L.Term α) → t.functionsIn ⊆ F → (funSublang (L := L) F).Term α
  | .var x, _ => .var x
  | .func f ts, h =>
    .func ⟨f, h (Set.mem_insert _ _)⟩
      (fun i => (ts i).restrictFuns
        (fun _ hx => h (Set.mem_insert_of_mem _ (Set.mem_iUnion.mpr ⟨i, hx⟩))))

/-- The inclusion is a left inverse of term restriction. -/
theorem Term.onTerm_restrictFuns {α : Type} {F : Set (Σ n, L.Functions n)} :
    ∀ (t : L.Term α) (h : t.functionsIn ⊆ F),
      (funSublangIncl F).onTerm (t.restrictFuns h) = t := by
  intro t
  induction t with
  | var x => intro h; rfl
  | func f ts ih =>
    intro h
    simp only [Term.restrictFuns, LHom.onTerm]
    exact congrArg _ (funext fun i => ih i _)

/-- Restrict a formula whose function symbols lie in `F` to the generated sublanguage (relations
pass through unchanged). -/
def BoundedFormulaω.restrictFuns {α : Type} {F : Set (Σ n, L.Functions n)} :
    ∀ {n : ℕ} (φ : L.BoundedFormulaω α n), φ.functionsIn ⊆ F →
      (funSublang (L := L) F).BoundedFormulaω α n
  | _, .falsum, _ => .falsum
  | _, .equal t u, h =>
    .equal (t.restrictFuns fun _ hx => h (Set.mem_union_left _ hx))
      (u.restrictFuns fun _ hx => h (Set.mem_union_right _ hx))
  | _, .rel R ts, h =>
    .rel R (fun i => (ts i).restrictFuns fun _ hx => h (Set.mem_iUnion.mpr ⟨i, hx⟩))
  | _, .imp φ ψ, h =>
    .imp (φ.restrictFuns fun _ hx => h (Set.mem_union_left _ hx))
      (ψ.restrictFuns fun _ hx => h (Set.mem_union_right _ hx))
  | _, .all φ, h => .all (φ.restrictFuns h)
  | _, .iSup φs, h =>
    .iSup fun i => (φs i).restrictFuns fun _ hx => h (Set.mem_iUnion.mpr ⟨i, hx⟩)
  | _, .iInf φs, h =>
    .iInf fun i => (φs i).restrictFuns fun _ hx => h (Set.mem_iUnion.mpr ⟨i, hx⟩)

/-- The inclusion is a left inverse of formula restriction: the restricted formula maps back to
the original. The bridge that lets the sublanguage EM model realize the original formulas. -/
theorem BoundedFormulaω.mapLanguage_restrictFuns {α : Type} {F : Set (Σ n, L.Functions n)} :
    ∀ {n : ℕ} (φ : L.BoundedFormulaω α n) (h : φ.functionsIn ⊆ F),
      (φ.restrictFuns h).mapLanguage (funSublangIncl F) = φ := by
  intro n φ
  induction φ with
  | falsum => intro h; rfl
  | equal t u =>
    intro h
    simp only [BoundedFormulaω.restrictFuns, BoundedFormulaω.mapLanguage,
      Term.onTerm_restrictFuns]
  | rel R ts =>
    intro h
    simp only [BoundedFormulaω.restrictFuns, BoundedFormulaω.mapLanguage]
    exact congrArg _ (funext fun i => Term.onTerm_restrictFuns (ts i) _)
  | imp φ ψ ihφ ihψ =>
    intro h
    simp only [BoundedFormulaω.restrictFuns, BoundedFormulaω.mapLanguage, ihφ, ihψ]
  | all φ ih =>
    intro h
    simp only [BoundedFormulaω.restrictFuns, BoundedFormulaω.mapLanguage, ih]
  | iSup φs ih =>
    intro h
    simp only [BoundedFormulaω.restrictFuns, BoundedFormulaω.mapLanguage]
    exact congrArg _ (funext fun i => ih i _)
  | iInf φs ih =>
    intro h
    simp only [BoundedFormulaω.restrictFuns, BoundedFormulaω.mapLanguage]
    exact congrArg _ (funext fun i => ih i _)

end FirstOrder.Language
