# Site settings

title: Infinitary Logic in Lean 4
email: freer@mit.edu
description: by Cameron Freer
baseurl: ""
url: "https://cameronfreer.github.io/infinitary-logic"
twitter_username:
github_username: cameronfreer
repository: cameronfreer/infinitary-logic

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
