/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import InfinitaryLogic.ModelTheory.TypeIsolation
import InfinitaryLogic.ModelTheory.FragmentLowenheimSkolem

/-!
# The controlling fragment and the countable companion (issue #17 chunk 2)

One countable seed controls the whole back-and-forth: over every arity it contains each
isolating formula `χ_p` of a realized type, and the one-variable existential closure
`(χ_p).ex` of every `(n+1)`-ary isolator (`BoundedFormulaω.ex` is `¬∀¬`, and `realize_ex`
quantifies exactly the coordinate added by `Fin.snoc` — no renaming formulas are needed). The
component-closed fragment it generates is countable, and the genuine downward Löwenheim–Skolem
theorem (#13) yields the countable companion `N ≺_A M`.

Still language-general (countable function symbols only — relationality first enters at the
BF/Scott packaging boundary, per the frozen audit).
-/

namespace FirstOrder

namespace Language

open Lomega1omega

variable {L : Language.{0, 0}} {M : Type} [L.Structure M]

/-- The controlling seed: all isolators, and the existential closures of all isolators of one
higher arity. -/
def isolatorSeed (hsmall : Lomega1omegaSmall (L := L) M) :
    Set (Σ n, L.BoundedFormulaω Empty n) :=
  (⋃ n : ℕ, (fun p : Set (L.BoundedFormulaω Empty n) =>
      (⟨n, isolatingFormula (hsmall n) p⟩ : Σ n, L.BoundedFormulaω Empty n)) ''
    RealizedInfinitaryTypes (L := L) M n)
  ∪ (⋃ n : ℕ, (fun p : Set (L.BoundedFormulaω Empty (n + 1)) =>
      (⟨n, (isolatingFormula (hsmall (n + 1)) p).ex⟩ : Σ n, L.BoundedFormulaω Empty n)) ''
    RealizedInfinitaryTypes (L := L) M (n + 1))

theorem isolatorSeed_countable (hsmall : Lomega1omegaSmall (L := L) M) :
    (isolatorSeed hsmall).Countable :=
  Set.Countable.union
    (Set.countable_iUnion fun n => (hsmall n).image _)
    (Set.countable_iUnion fun n => (hsmall (n + 1)).image _)

/-- **The controlling fragment**: the component-closed fragment generated by the seed. -/
def isolatorFragment (hsmall : Lomega1omegaSmall (L := L) M) : Fragment L :=
  Fragment.generated (isolatorSeed hsmall)

theorem isolatorFragment_countable (hsmall : Lomega1omegaSmall (L := L) M) :
    (isolatorFragment hsmall).toSet.Countable :=
  Fragment.generated_countable (isolatorSeed_countable hsmall)

theorem isolatingFormula_mem_isolatorFragment (hsmall : Lomega1omegaSmall (L := L) M)
    {n : ℕ} {p : Set (L.BoundedFormulaω Empty n)}
    (hp : p ∈ RealizedInfinitaryTypes (L := L) M n) :
    (⟨n, isolatingFormula (hsmall n) p⟩ : Σ n, L.BoundedFormulaω Empty n)
      ∈ (isolatorFragment hsmall).toSet :=
  Fragment.subset_generated _ (Set.mem_union_left _
    (Set.mem_iUnion.mpr ⟨n, Set.mem_image_of_mem _ hp⟩))

theorem isolatingFormula_ex_mem_isolatorFragment (hsmall : Lomega1omegaSmall (L := L) M)
    {n : ℕ} {p : Set (L.BoundedFormulaω Empty (n + 1))}
    (hp : p ∈ RealizedInfinitaryTypes (L := L) M (n + 1)) :
    (⟨n, (isolatingFormula (hsmall (n + 1)) p).ex⟩ : Σ n, L.BoundedFormulaω Empty n)
      ∈ (isolatorFragment hsmall).toSet :=
  Fragment.subset_generated _ (Set.mem_union_right _
    (Set.mem_iUnion.mpr ⟨n, Set.mem_image_of_mem _ hp⟩))

/-- **The countable companion** (issue #17 chunk 2 endpoint): a small structure over countably
many function symbols has a countable substructure that is elementary for the controlling
fragment. -/
theorem exists_countable_companion [Countable (Σ n, L.Functions n)]
    (hsmall : Lomega1omegaSmall (L := L) M) :
    ∃ N : L.Substructure M, Countable N ∧ AElementary (isolatorFragment hsmall) N.subtype := by
  obtain ⟨N, _, hAe, hcnt⟩ := exists_countable_aElementary_substructure
    (isolatorFragment hsmall) (X := (∅ : Set M)) Set.countable_empty
    (isolatorFragment_countable hsmall)
  exact ⟨N, hcnt, hAe⟩

end Language

end FirstOrder
