/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import InfinitaryLogic.ModelTheory.AElementary
import InfinitaryLogic.ModelTheory.HanfSpectrum.CardinalBounds
import Mathlib.ModelTheory.Substructures

/-!
# Genuine downward Löwenheim–Skolem for fragments (issue #13 unit 5)

Per the frozen audit (`docs/fragments-audit.md` §5–§6): from an arbitrary `M` and `X ⊆ M`,
construct an A-elementary substructure containing `X` with the HONEST cardinal bound

  `|N| ≤ max(ℵ₀, |X|, |A|, |Σ n, L.Functions n|)`.

The construction is the semantic witness hull (Marker, Exercise 1.23, presented with choice
functions instead of a language expansion): interleave `Substructure.closure` (all language
functions — this is where `|Σ Functions|` honestly enters) with chosen witnesses for failures
of the fragment-controlled universals (`tvWitnessSet` — `|A|`-many witness suppliers), iterate
ω times, and close once more. The union is closed under both, so the Tarski–Vaught criterion
(`aElementary_of_tarskiVaught`) applies. Witnesses are extracted from existence proofs
(`Exists.choose`), so no `Nonempty M` hypothesis and no dummy elements are needed.

Marker's textbook bound `max(|A|,|X|)` (Theorem 1.22) is the corollary
`mk_le_of_functions_le` under `|Σ Functions| ≤ max ℵ₀ |A|`; the countable corollary is
`exists_countable_aElementary_substructure`. The file is stated for `Language.{0,0}` and
`Type 0` carriers — the consumers' setting.
-/

namespace FirstOrder

namespace Language

open Cardinal

variable {L : Language.{0, 0}} {M : Type} [L.Structure M] (A : Fragment L)

/-! ## The witness sets and the hull -/

/-- The chosen witnesses over a base set `Y`: for each fragment-controlled universal and each
tuple from `Y` admitting a counterexample in `M`, THE chosen counterexample. -/
def tvWitnessSet (Y : Set M) : Set M :=
  {m | ∃ (n : ℕ) (φ : L.BoundedFormulaω Empty (n + 1)) (a : Fin n → M),
    ((⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet ∧ ∀ i, a i ∈ Y) ∧
    ∃ h : ∃ m' : M, ¬φ.Realize Empty.elim (Fin.snoc a m'), m = h.choose}

/-- The Löwenheim–Skolem stages: alternately close under all language functions and add the
fragment witnesses. -/
def lsStage (X : Set M) : ℕ → Set M
  | 0 => X
  | k + 1 => (Substructure.closure L (lsStage X k) : Set M)
      ∪ tvWitnessSet A ((Substructure.closure L (lsStage X k) : Set M))

theorem lsStage_mono (X : Set M) : ∀ k, lsStage A X k ⊆ lsStage A X (k + 1) := fun _ =>
  le_trans (Substructure.subset_closure (L := L)) Set.subset_union_left

theorem lsStage_mono_le (X : Set M) : Monotone (lsStage A X) :=
  monotone_nat_of_le_succ (lsStage_mono A X)

/-- **The witness hull**: the substructure generated by all stages. -/
def lsHull (X : Set M) : L.Substructure M :=
  Substructure.closure L (⋃ k, lsStage A X k)

theorem subset_lsHull (X : Set M) : X ⊆ (lsHull A X : Set M) :=
  le_trans (Set.subset_iUnion (lsStage A X) 0) (Substructure.subset_closure (L := L))

/-- The hull's carrier is the union of the stage closures — directedness makes the last
closure redundant. -/
theorem coe_lsHull (X : Set M) :
    (lsHull A X : Set M) = ⋃ k, (Substructure.closure L (lsStage A X k) : Set M) := by
  apply Set.Subset.antisymm
  · intro x hx
    rw [lsHull] at hx
    have hsub : (⋃ k, lsStage A X k)
        ⊆ ⋃ k, (Substructure.closure L (lsStage A X k) : Set M) :=
      Set.iUnion_mono fun k => Substructure.subset_closure (L := L)
    -- the union of the closures is itself (the carrier of) a substructure, by directedness
    have hdir : Directed (· ≤ ·) fun k => Substructure.closure L (lsStage A X k) := by
      intro i j
      exact ⟨max i j, Substructure.closure_mono (lsStage_mono_le A X (le_max_left i j)),
        Substructure.closure_mono (lsStage_mono_le A X (le_max_right i j))⟩
    have hmem := (Substructure.closure_le
      (S := ⨆ k, Substructure.closure L (lsStage A X k))).mpr
      (le_trans hsub (by
        intro y hy
        obtain ⟨k, hk⟩ := Set.mem_iUnion.mp hy
        exact (Substructure.mem_iSup_of_directed hdir).mpr ⟨k, hk⟩)) hx
    obtain ⟨k, hk⟩ := (Substructure.mem_iSup_of_directed hdir).mp hmem
    exact Set.mem_iUnion.mpr ⟨k, hk⟩
  · refine Set.iUnion_subset fun k => ?_
    exact Substructure.closure_mono (Set.subset_iUnion (lsStage A X) k)

/-- Finitely many hull elements lie in a common stage closure. -/
theorem exists_stage_of_tuple {X : Set M} {n : ℕ} (a : Fin n → lsHull A X) :
    ∃ K, ∀ i, (a i : M) ∈ (Substructure.closure L (lsStage A X K) : Set M) := by
  have hmem : ∀ i, ∃ k, (a i : M) ∈ (Substructure.closure L (lsStage A X k) : Set M) := by
    intro i
    have h := (a i).2
    have h2 : (a i : M) ∈ (lsHull A X : Set M) := h
    rw [coe_lsHull A X] at h2
    exact Set.mem_iUnion.mp h2
  choose ks hks using hmem
  refine ⟨Finset.univ.sup ks, fun i => ?_⟩
  exact Substructure.closure_mono
    (lsStage_mono_le A X (Finset.le_sup (Finset.mem_univ i))) (hks i)

/-- **The hull is A-elementary** — the Tarski–Vaught criterion holds by construction. -/
theorem aElementary_lsHull (X : Set M) :
    AElementary A ((lsHull A X).subtype) := by
  refine aElementary_of_tarskiVaught _ ?_
  intro n φ hφ a hex
  obtain ⟨K, hK⟩ := exists_stage_of_tuple A a
  have hwmem : hex.choose ∈ (lsHull A X : Set M) := by
    have h1 : hex.choose ∈ tvWitnessSet A
        ((Substructure.closure L (lsStage A X K) : Set M)) :=
      ⟨n, φ, _, ⟨hφ, hK⟩, hex, rfl⟩
    have h2 : hex.choose ∈ lsStage A X (K + 1) := Set.mem_union_right _ h1
    exact Substructure.subset_closure (L := L) (Set.mem_iUnion.mpr ⟨K + 1, h2⟩)
  exact ⟨⟨hex.choose, hwmem⟩, hex.choose_spec⟩

/-! ## The cardinal bound -/

/-- The per-arity witness suppliers: fragment-controlled bodies paired with tuples from `Y`. -/
def tvSlice (Y : Set M) (n : ℕ) : Type :=
  {q : L.BoundedFormulaω Empty (n + 1) × (Fin n → M) //
    (⟨n, q.1.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet ∧ ∀ i, q.2 i ∈ Y}

open Classical in
/-- The choice map from a slice: the chosen counterexample, when one exists. -/
noncomputable def tvSliceWitness (Y : Set M) (n : ℕ) : tvSlice A Y n → Option M := fun q =>
  if h : ∃ m' : M, ¬q.1.1.Realize Empty.elim (Fin.snoc q.1.2 m') then some h.choose else none

theorem tvWitnessSet_subset_iUnion (Y : Set M) :
    tvWitnessSet A Y ⊆ ⋃ n : ℕ, Option.some ⁻¹' Set.range (tvSliceWitness A Y n) := by
  rintro m ⟨n, φ, a, ⟨hφ, ha⟩, hex, rfl⟩
  refine Set.mem_iUnion.mpr ⟨n, ⟨⟨(φ, a), hφ, ha⟩, ?_⟩⟩
  show tvSliceWitness A Y n ⟨(φ, a), hφ, ha⟩ = some hex.choose
  rw [tvSliceWitness, dif_pos hex]

omit [L.Structure M] in
theorem mk_tvSlice_le (Y : Set M) (n : ℕ) :
    Cardinal.mk (tvSlice A Y n)
      ≤ max (max Cardinal.aleph0 (Cardinal.mk Y)) (Cardinal.mk A.toSet) := by
  set κ := max (max Cardinal.aleph0 (Cardinal.mk Y)) (Cardinal.mk A.toSet) with hκ
  have hκinf : Cardinal.aleph0 ≤ κ := le_trans (le_max_left _ _) (le_max_left _ _)
  have hinj : Function.Injective (fun q : tvSlice A Y n =>
      ((⟨q.1.1, q.2.1⟩, fun i => ⟨q.1.2 i, q.2.2 i⟩) :
        {φ : L.BoundedFormulaω Empty (n + 1) //
          (⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet} × (Fin n → Y))) := by
    intro q r h
    have h1 : q.1.1 = r.1.1 := congrArg (fun p => (p.1 : L.BoundedFormulaω Empty (n + 1))) h
    have h2 : q.1.2 = r.1.2 := funext fun i =>
      congrArg (fun p => (p.2 i : M)) h
    exact Subtype.ext (Prod.ext h1 h2)
  have hφle : Cardinal.mk {φ : L.BoundedFormulaω Empty (n + 1) //
      (⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet} ≤ Cardinal.mk A.toSet := by
    refine Cardinal.mk_le_of_injective (f := fun φ => (⟨⟨n, φ.1.all⟩, φ.2⟩ : A.toSet)) ?_
    intro φ ψ h
    have h1 : (⟨n, φ.1.all⟩ : Σ n, L.BoundedFormulaω Empty n) = ⟨n, ψ.1.all⟩ :=
      congrArg Subtype.val h
    have h2 : φ.1.all = ψ.1.all := eq_of_heq (Sigma.mk.injEq .. ▸ h1).2
    exact Subtype.ext (by injection h2)
  have hYle : Cardinal.mk (Fin n → Y) ≤ max Cardinal.aleph0 (Cardinal.mk Y) := by
    have hpow : Cardinal.mk (Fin n → Y) = Cardinal.mk Y ^ (n : Cardinal) := by
      rw [← Cardinal.power_def, Cardinal.mk_fin]
    rw [hpow]
    calc Cardinal.mk Y ^ (n : Cardinal)
        ≤ (max Cardinal.aleph0 (Cardinal.mk Y)) ^ (n : Cardinal) :=
          Cardinal.power_le_power_right (le_max_right _ _)
      _ ≤ max Cardinal.aleph0 (Cardinal.mk Y) :=
          Cardinal.pow_le (le_max_left _ _) Cardinal.natCast_lt_aleph0
  calc Cardinal.mk (tvSlice A Y n)
      ≤ Cardinal.mk ({φ : L.BoundedFormulaω Empty (n + 1) //
          (⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet} × (Fin n → Y)) :=
        Cardinal.mk_le_of_injective hinj
    _ = Cardinal.mk {φ : L.BoundedFormulaω Empty (n + 1) //
          (⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet} * Cardinal.mk (Fin n → Y) := by
        rw [Cardinal.mk_prod, Cardinal.lift_id, Cardinal.lift_id]
    _ ≤ κ * κ := mul_le_mul' (hφle.trans (le_max_right _ _))
        (hYle.trans (le_max_left _ _))
    _ = κ := Cardinal.mul_eq_self hκinf

theorem mk_tvWitnessSet_le (Y : Set M) :
    Cardinal.mk (tvWitnessSet A Y)
      ≤ max (max Cardinal.aleph0 (Cardinal.mk Y)) (Cardinal.mk A.toSet) := by
  refine le_trans (Cardinal.mk_le_mk_of_subset (tvWitnessSet_subset_iUnion A Y)) ?_
  refine FirstOrder.HanfLadder.mk_iUnion_le_of_countable
    (le_trans (le_max_left _ _) (le_max_left _ _)) fun n => ?_
  exact le_trans (Cardinal.mk_preimage_of_injective _ _ (Option.some_injective _))
    (le_trans (Cardinal.mk_range_le) (mk_tvSlice_le A Y n))

/-- The honest per-stage bound. -/
theorem mk_lsStage_le (X : Set M) (k : ℕ) :
    Cardinal.mk (lsStage A X k)
      ≤ max (max Cardinal.aleph0 (Cardinal.mk X))
          (max (Cardinal.mk A.toSet) (Cardinal.mk (Σ n, L.Functions n))) := by
  set κ := max (max Cardinal.aleph0 (Cardinal.mk X))
    (max (Cardinal.mk A.toSet) (Cardinal.mk (Σ n, L.Functions n))) with hκ
  have hκinf : Cardinal.aleph0 ≤ κ := le_trans (le_max_left _ _) (le_max_left _ _)
  have hF : Cardinal.mk (Σ n, L.Functions n) ≤ κ :=
    le_trans (le_max_right (Cardinal.mk A.toSet) _) (le_max_right _ _)
  have hclosure : ∀ Y : Set M, Cardinal.mk Y ≤ κ →
      Cardinal.mk (Substructure.closure L Y : Set M) ≤ κ := by
    intro Y hY
    have h := Substructure.lift_card_closure_le (L := L) (s := Y)
    rw [Cardinal.lift_id, Cardinal.lift_id, Cardinal.lift_id] at h
    refine le_trans h (max_le hκinf ?_)
    calc Cardinal.mk Y + Cardinal.mk (Σ n, L.Functions n) ≤ κ + κ := add_le_add hY hF
      _ = κ := Cardinal.add_eq_self hκinf
  induction k with
  | zero => exact le_trans (le_max_right _ _) (le_max_left _ _)
  | succ k ih =>
    have hclk := hclosure (lsStage A X k) ih
    refine le_trans (Cardinal.mk_union_le _ _) ?_
    have hW : Cardinal.mk (tvWitnessSet A
        ((Substructure.closure L (lsStage A X k) : Set M))) ≤ κ := by
      refine le_trans (mk_tvWitnessSet_le A _) (max_le (max_le hκinf hclk) ?_)
      exact le_trans (le_max_left _ _) (le_max_right _ _)
    calc Cardinal.mk (Substructure.closure L (lsStage A X k) : Set M)
          + Cardinal.mk (tvWitnessSet A ((Substructure.closure L (lsStage A X k) : Set M)))
        ≤ κ + κ := add_le_add hclk hW
      _ = κ := Cardinal.add_eq_self hκinf

/-- **The honest hull bound**: `|N| ≤ max(ℵ₀, |X|, |A|, |Σ Functions|)`. -/
theorem mk_lsHull_le (X : Set M) :
    Cardinal.mk (lsHull A X)
      ≤ max (max Cardinal.aleph0 (Cardinal.mk X))
          (max (Cardinal.mk A.toSet) (Cardinal.mk (Σ n, L.Functions n))) := by
  set κ := max (max Cardinal.aleph0 (Cardinal.mk X))
    (max (Cardinal.mk A.toSet) (Cardinal.mk (Σ n, L.Functions n))) with hκ
  have hκinf : Cardinal.aleph0 ≤ κ := le_trans (le_max_left _ _) (le_max_left _ _)
  have hunion : Cardinal.mk (⋃ k, lsStage A X k) ≤ κ :=
    FirstOrder.HanfLadder.mk_iUnion_le_of_countable hκinf (mk_lsStage_le A X)
  have hF : Cardinal.mk (Σ n, L.Functions n) ≤ κ :=
    le_trans (le_max_right (Cardinal.mk A.toSet) _) (le_max_right _ _)
  have h := Substructure.lift_card_closure_le (L := L) (s := ⋃ k, lsStage A X k)
  rw [Cardinal.lift_id, Cardinal.lift_id, Cardinal.lift_id] at h
  refine le_trans h (max_le hκinf ?_)
  calc Cardinal.mk (⋃ k, lsStage A X k) + Cardinal.mk (Σ n, L.Functions n)
      ≤ κ + κ := add_le_add hunion hF
    _ = κ := Cardinal.add_eq_self hκinf

/-- **Genuine downward Löwenheim–Skolem for fragments** (issue #13 unit 5): every `X ⊆ M` is
contained in an A-elementary substructure of size at most `max(ℵ₀, |X|, |A|, |Σ Functions|)` —
the honest bound; only function symbols enlarge the hull beyond the fragment's witnesses. -/
theorem exists_aElementary_substructure (A : Fragment L) (X : Set M) :
    ∃ N : L.Substructure M, X ⊆ (N : Set M) ∧ AElementary A N.subtype ∧
      Cardinal.mk N ≤ max (max Cardinal.aleph0 (Cardinal.mk X))
        (max (Cardinal.mk A.toSet) (Cardinal.mk (Σ n, L.Functions n))) :=
  ⟨lsHull A X, subset_lsHull A X, aElementary_lsHull A X, mk_lsHull_le A X⟩

/-- **The countable corollary** (Marker, Theorem 1.22 second half — what #17 consumes):
countable data yields a countable A-elementary substructure. -/
theorem exists_countable_aElementary_substructure (A : Fragment L) {X : Set M}
    (hX : X.Countable) (hA : A.toSet.Countable)
    [hF : Countable (Σ n, L.Functions n)] :
    ∃ N : L.Substructure M, X ⊆ (N : Set M) ∧ AElementary A N.subtype ∧ Countable N := by
  obtain ⟨N, hXN, hAe, hcard⟩ := exists_aElementary_substructure A X
  refine ⟨N, hXN, hAe, ?_⟩
  rw [← Cardinal.mk_le_aleph0_iff]
  refine le_trans hcard (max_le (max_le le_rfl ?_) (max_le ?_ ?_))
  · haveI := hX.to_subtype
    exact Cardinal.mk_le_aleph0
  · haveI := hA.to_subtype
    exact Cardinal.mk_le_aleph0
  · exact Cardinal.mk_le_aleph0

end Language

end FirstOrder
