/-
Regression guard for the free-set lemma and its generation corollaries
(`InfinitaryLogic/FreeSetBound.lean`).

Checked: the **base case** on `ℕ` (a finite-valued map, `ℵ_(0 + 0) ≤ #ℕ`, yields an independent
singleton); a **genuine pair** on the uncountable carrier `ℕ → Bool` (`ℵ_(0 + 1) ≤ 𝔠`, a
finite-valued map, an independent pair); **singleton generation** (`n = 1`) on the closure
`S ↦ [0, max S]` of `ℕ`, which needs one generator and not zero, giving `#ℕ < ℵ_ 1` and no
independent pair; the **identity closure**, whose hull map makes every finite set independent (so
on `Fin 3` there is an independent triple, consistent with the failure of whole-hull
two-generation there) and which has pair witnesses for every membership on a carrier above `ℵ₁`
while the `ℵ₁` bound fails, so pair witnesses must not replace whole-hull generation; and
**compatibility with `mk_le_aleph_one`**: for an arbitrary two-generated closure, `#M ≤ ℵ₁` is
derived from `mk_lt_aleph_of_generation` at `n = 2` and obtained from the original bound applied
to the same hypotheses, and the constant closure on `Fin 3` is checked at `n = 0` and `n = 2`.
Headline declarations use only the standard axioms.

Run with: lake env lean scripts/check_free_set_bound_regressions.lean
-/
import InfinitaryLogic.FreeSetBound
import InfinitaryLogic.TwoGeneratorCardinality
import Mathlib.SetTheory.Cardinal.Continuum

open Lean Cardinal InfinitaryLogic.FreeSet InfinitaryLogic.FiniteSupportClosure

universe u

/-! ### The base case on a countable carrier -/

/-- **Base case**: the finite-valued map `A ↦ [0, max A]` on `ℕ` has an independent
singleton. -/
theorem base_case_regression :
    ∃ A : Finset ℕ, A.card = 1 ∧
      FIndependent (fun A : Finset ℕ ↦ (↑(Finset.range (A.sup id + 1)) : Set ℕ)) A := by
  refine exists_fIndependent (fun A : Finset ℕ ↦ (↑(Finset.range (A.sup id + 1)) : Set ℕ)) 0 0
    (fun A ↦ ?_) ?_
  · rw [aleph_zero]
    exact (Finset.finite_toSet _).lt_aleph0
  · simp

/-! ### A genuine pair on an uncountable carrier -/

/-- The pointwise complement of a binary sequence. -/
def negSeq (x : ℕ → Bool) : ℕ → Bool := fun n ↦ !x n

/-- **Uncountable pair**: on `ℕ → Bool` (cardinality `𝔠 ≥ ℵ₁`), the finite-valued map sending a
finite set to itself together with the complements of its members has an independent pair. -/
theorem uncountable_pair_regression :
    ∃ A : Finset (ℕ → Bool), A.card = 2 ∧
      FIndependent (fun A ↦ (↑A ∪ negSeq '' ↑A : Set (ℕ → Bool))) A := by
  refine exists_fIndependent (fun A ↦ (↑A ∪ negSeq '' ↑A : Set (ℕ → Bool))) 0 1
    (fun A ↦ ?_) ?_
  · rw [aleph_zero]
    exact (A.finite_toSet.union (A.finite_toSet.image _)).lt_aleph0
  · have h : #(ℕ → Bool) = 𝔠 := by simp
    rw [h, Nat.cast_one, zero_add]
    exact aleph_one_le_continuum

/-! ### Singleton generation -/

/-- The closure `S ↦ [0, max S]` on the finite subsets of `ℕ` (with `∅ ↦ {0}`). -/
def rangeClosure : ClosureOperator (Finset ℕ) :=
  ClosureOperator.mk' (fun S ↦ Finset.range (S.sup id + 1))
    (fun _ _ h ↦ Finset.range_subset_range.mpr (Nat.succ_le_succ (Finset.sup_mono h)))
    (fun _ _ hx ↦ Finset.mem_range.mpr (Nat.lt_succ_of_le (Finset.le_sup (f := id) hx)))
    (fun _ ↦ Finset.range_subset_range.mpr (Nat.succ_le_succ
      (Finset.sup_le fun _ hb ↦ Nat.lt_succ_iff.mp (Finset.mem_range.mp hb))))

/-- Every hull of `rangeClosure` is the hull of at most one point, its maximum. -/
theorem rangeClosure_generation :
    ∀ S, ∃ T ⊆ S, T.card ≤ 1 ∧ rangeClosure T = rangeClosure S := by
  intro S
  rcases S.eq_empty_or_nonempty with rfl | hS
  · exact ⟨∅, subset_rfl, by simp, rfl⟩
  · obtain ⟨i, hi, hsup⟩ := Finset.exists_mem_eq_sup S hS id
    refine ⟨{i}, Finset.singleton_subset_iff.mpr hi, by simp, ?_⟩
    change Finset.range (({i} : Finset ℕ).sup id + 1) = Finset.range (S.sup id + 1)
    rw [Finset.sup_singleton, hsup]

/-- **Singleton generation** (`n = 1`): `rangeClosure` is generated by at most one point but not
by none, the generation bound gives `#ℕ < ℵ_ 1`, and no pair is independent for its hull map. -/
theorem singleton_generation_regression :
    ¬ (∀ S, ∃ T ⊆ S, T.card ≤ 0 ∧ rangeClosure T = rangeClosure S) ∧
      #ℕ < ℵ_ (1 : ℕ) ∧
      ¬ FIndependent (fun S ↦ (↑(rangeClosure S) : Set ℕ)) {0, 1} := by
  refine ⟨fun h ↦ ?_, mk_lt_aleph_of_generation rangeClosure rangeClosure_generation,
    not_fIndependent_of_generation rangeClosure rangeClosure_generation (by simp)⟩
  obtain ⟨T, -, hT, heq⟩ := h {1}
  rw [Finset.card_eq_zero.mp (Nat.le_zero.mp hT)] at heq
  have h1 : (1 : ℕ) ∈ rangeClosure {1} := rangeClosure.le_closure _ (Finset.mem_singleton_self 1)
  rw [← heq] at h1
  change 1 ∈ Finset.range ((∅ : Finset ℕ).sup id + 1) at h1
  simp at h1

/-! ### The identity closure -/

/-- The identity closure on the finite subsets of `M`. -/
def idClosure (M : Type) : ClosureOperator (Finset M) := ClosureOperator.id (Finset M)

/-- For the identity closure every finite set is independent for the hull map. -/
theorem idClosure_fIndependent (M : Type) (A : Finset M) :
    FIndependent (fun S ↦ (↑(idClosure M S) : Set M)) A :=
  fun _ _ _ _ haB haf ↦ haB haf

/-- **Three points**: the identity closure on `Fin 3` has an independent triple, and whole-hull
two-generation fails there, as the generation bound at `n = 2` predicts. -/
theorem three_point_regression :
    FIndependent (fun S ↦ (↑(idClosure (Fin 3) S) : Set (Fin 3))) Finset.univ ∧
    ¬ (∀ S : Finset (Fin 3), ∃ T ⊆ S, T.card ≤ 2 ∧ idClosure (Fin 3) T = idClosure (Fin 3) S) :=
  ⟨idClosure_fIndependent _ _, fun hgen ↦
    not_fIndependent_of_generation _ hgen (A := Finset.univ) (by simp)
      (idClosure_fIndependent _ _)⟩

/-- **Pair witnesses give no bound**: on a carrier of cardinality above `ℵ₁`, the identity closure
has pair witnesses for every membership while `#M ≤ ℵ₁` fails. -/
theorem large_carrier_regression :
    (∀ (S : Finset (Set (ℕ → Bool))) (x : Set (ℕ → Bool)),
      x ∈ idClosure (Set (ℕ → Bool)) S →
        ∃ T ⊆ S, T.card ≤ 2 ∧ x ∈ idClosure (Set (ℕ → Bool)) T) ∧
    ¬ (#(Set (ℕ → Bool)) ≤ ℵ₁) := by
  classical
  refine ⟨fun S x hx ↦ ⟨{x}, Finset.singleton_subset_iff.mpr hx, by simp,
    by simp [idClosure]⟩, fun h ↦ ?_⟩
  have h1 : #(Set (ℕ → Bool)) = 2 ^ #(ℕ → Bool) := Cardinal.mk_set
  have h2 : #(ℕ → Bool) = 𝔠 := by simp
  rw [h1, h2] at h
  exact absurd (h.trans Cardinal.aleph_one_le_continuum) (not_le.mpr (Cardinal.cantor 𝔠))

/-! ### Compatibility with `mk_le_aleph_one` -/

/-- A cardinal below `ℵ_ 2` is at most `ℵ₁`. -/
theorem le_aleph_one_of_lt_aleph_two {κ : Cardinal.{u}} (h : κ < ℵ_ (2 : ℕ)) : κ ≤ ℵ₁ := by
  rw [← Order.lt_succ_iff, succ_aleph, one_add_one_eq_two]
  simpa using h

/-- **Both derivations**: under whole-hull two-generation, the generation bound at `n = 2` gives
`#M < ℵ_ 2`, hence `#M ≤ ℵ₁`; the original bound gives `#M ≤ ℵ₁` from the same hypotheses; and no
set with more than two elements is independent for the hull map. -/
theorem compatibility_regression {M : Type u} (c : ClosureOperator (Finset M))
    (hgen : ∀ S, ∃ T ⊆ S, T.card ≤ 2 ∧ c T = c S) :
    #M < ℵ_ (2 : ℕ) ∧ #M ≤ ℵ₁ ∧ #M ≤ ℵ₁ ∧
      ∀ A : Finset M, 2 < A.card → ¬ FIndependent (fun S ↦ (↑(c S) : Set M)) A :=
  ⟨mk_lt_aleph_of_generation c hgen,
    le_aleph_one_of_lt_aleph_two (mk_lt_aleph_of_generation c hgen), mk_le_aleph_one c hgen,
    fun _ hA ↦ not_fIndependent_of_generation c hgen hA⟩

/-- The constant closure on `Fin 3`: every finite set has the whole carrier as its hull. -/
def topClosure : ClosureOperator (Finset (Fin 3)) :=
  ClosureOperator.mk' (fun _ ↦ Finset.univ) (fun _ _ _ ↦ le_rfl)
    (fun _ ↦ Finset.subset_univ _) (fun _ ↦ le_rfl)

/-- **A concrete generated closure**: the constant closure on `Fin 3` is generated by the empty
set; at `n = 0` the carrier is finite and no singleton is independent, and at `n = 2` both
derivations bound the carrier by `ℵ₁` and the whole carrier is not an independent triple. -/
theorem top_closure_regression :
    #(Fin 3) < ℵ_ (0 : ℕ) ∧
      ¬ FIndependent (fun S ↦ (↑(topClosure S) : Set (Fin 3))) {0} ∧
      #(Fin 3) ≤ ℵ₁ ∧ #(Fin 3) ≤ ℵ₁ ∧
      ¬ FIndependent (fun S ↦ (↑(topClosure S) : Set (Fin 3))) Finset.univ := by
  have hgen : ∀ n : ℕ, ∀ S, ∃ T ⊆ S, T.card ≤ n ∧ topClosure T = topClosure S :=
    fun _ S ↦ ⟨∅, Finset.empty_subset S, by simp, rfl⟩
  exact ⟨mk_lt_aleph_of_generation topClosure (hgen 0),
    not_fIndependent_of_generation topClosure (hgen 0) (by simp),
    le_aleph_one_of_lt_aleph_two (mk_lt_aleph_of_generation topClosure (hgen 2)),
    mk_le_aleph_one topClosure (hgen 2),
    not_fIndependent_of_generation topClosure (hgen 2) (by simp)⟩

/-! ### The all-subsets definition on a non-monotone map -/

/-- A non-monotone map: `f ∅ = {0}` and `f B = ∅` for nonempty `B`. -/
def spikeAtEmpty (B : Finset ℕ) : Set ℕ := if B = ∅ then {0} else ∅

theorem spikeAtEmpty_not_monotone : ¬ Monotone spikeAtEmpty := by
  intro h
  have h0 : (0 : ℕ) ∈ spikeAtEmpty ∅ := by simp [spikeAtEmpty]
  have := h (Finset.empty_subset ({1} : Finset ℕ)) h0
  simp [spikeAtEmpty] at this

/-- **Non-monotone case.**  On `A = {0, 1}` the erase-only condition `a ∉ f (A.erase a)` holds
for both points (the erased sets are nonempty, so `f` is empty there), yet `A` is **not**
`f`-independent: the subset `∅ ⊆ A` omits `0` and `0 ∈ f ∅`.  This is why `FIndependent`
quantifies over all subsets and why the induction needs the two-summand auxiliary map. -/
theorem non_monotone_regression :
    (∀ a ∈ ({0, 1} : Finset ℕ), a ∉ spikeAtEmpty (({0, 1} : Finset ℕ).erase a)) ∧
    ¬ FIndependent spikeAtEmpty {0, 1} := by
  refine ⟨fun a ha => ?_, fun h => ?_⟩
  · have hne : ({0, 1} : Finset ℕ).erase a ≠ ∅ := by
      intro he
      have := Finset.card_erase_of_mem ha
      rw [he] at this
      simp at this
    simp [spikeAtEmpty, hne]
  · have := h ∅ (Finset.empty_subset _) 0 (by simp) (by simp)
    simp [spikeAtEmpty] at this

/-! ### Axiom hygiene -/

def headline : List Name :=
  [`InfinitaryLogic.FreeSet.FIndependent,
   `InfinitaryLogic.FreeSet.fClosure,
   `InfinitaryLogic.FreeSet.subset_fClosure,
   `InfinitaryLogic.FreeSet.fClosure_closed,
   `InfinitaryLogic.FreeSet.fClosure_subset,
   `InfinitaryLogic.FreeSet.mk_fClosure_le,
   `InfinitaryLogic.FreeSet.exists_fIndependent,
   `InfinitaryLogic.FreeSet.not_fIndependent_of_generation,
   `InfinitaryLogic.FreeSet.mk_lt_aleph_of_generation,
   `non_monotone_regression, `spikeAtEmpty_not_monotone, `base_case_regression,
   `uncountable_pair_regression, `singleton_generation_regression,
   `three_point_regression, `large_carrier_regression, `compatibility_regression,
   `top_closure_regression]

def standardAxioms : List Name := [`propext, `Classical.choice, `Quot.sound]

run_cmd do
  let env ← getEnv
  for n in headline do
    unless (env.find? n).isSome do throwError "headline declaration {n} not found"
    let axs ← Elab.Command.liftCoreM (collectAxioms n)
    let bad := axs.toList.filter fun a ↦ !standardAxioms.contains a
    unless bad.isEmpty do throwError "[NONSTANDARD AXIOMS] {n} uses {bad}"
  logInfo "free-set bound regression guard: OK (base case on ℕ; independent pair on the \
    uncountable carrier ℕ → Bool; singleton generation on ℕ: #ℕ < ℵ_ 1, no independent pair; \
    identity closure: independent triple on Fin 3 and pair witnesses with no bound on a large \
    carrier; ℵ₁ bound derived from the generation bound at n = 2 alongside the original, on an \
    arbitrary two-generated closure and on the constant closure, also checked at n = 0; \
    headline declarations on standard axioms)"
