/-
Regression guard for the fragment-type / back-and-forth adapters (comparison audit, step 2).

Adapter A must apply at level zero to any fragment whose slice is empty, adapter B must apply
to the fragment generated by the bounded Scott formula of the source tuple (membership by
`subset_generated`, never by countability), and the headline declarations must use only the
standard axioms.  No test derives fragment elementarity from either adapter.

Run with: lake env lean scripts/check_fragment_bf_adapters.lean
-/
import InfinitaryLogic.ModelTheory.FragmentBFAdapters

open Lean FirstOrder Language

variable {L : Language.{u, v}} [L.IsRelational]

omit [L.IsRelational] in
theorem generatedFrom_empty (p : Σ n, L.BoundedFormulaω Empty n) :
    ¬ Fragment.GeneratedFrom (∅ : Set (Σ n, L.BoundedFormulaω Empty n)) p := by
  intro h
  induction h with
  | base h => exact h
  | imp_left _ ih => exact ih
  | imp_right _ ih => exact ih
  | all_body _ ih => exact ih
  | iInf_comp _ _ ih => exact ih
  | iSup_comp _ _ ih => exact ih

/-- A at level zero on the empty fragment: the slice is empty, the rank bound is vacuous. -/
theorem adapterA_empty_regression {M N : Type w} [L.Structure M] [L.Structure N] {n : ℕ}
    {a : Fin n → M} {b : Fin n → N} (h : BFEquiv (L := L) (0 : Ordinal.{0}) n a b) :
    (Fragment.generated (∅ : Set (Σ n, L.BoundedFormulaω Empty n))).realizedType M a =
      (Fragment.generated ∅).realizedType N b :=
  Fragment.realizedType_eq_of_bfEquiv _ h fun φ => absurd φ.2 (generatedFrom_empty _)

/-- B on the fragment generated by the source tuple's bounded Scott formula: membership comes
from `subset_generated`, not from any countability of the fragment. -/
theorem adapterB_generated_regression [Countable (Σ l, L.Relations l)] {M : Type w}
    [L.Structure M] [Countable M] {N : Type w'} [L.Structure N] {α : Ordinal}
    (hα : α < Ordinal.omega 1) {n : ℕ} {a : Fin n → M} {b : Fin n → N}
    (h : (Fragment.generated ({⟨n, Fragment.scottBounded (L := L) a α⟩} :
        Set (Σ n, L.BoundedFormulaω Empty n))).realizedType M a =
      (Fragment.generated ({⟨n, Fragment.scottBounded (L := L) a α⟩} :
        Set (Σ n, L.BoundedFormulaω Empty n))).realizedType N b) :
    BFEquiv (L := L) α n a b :=
  Fragment.bfEquiv_of_realizedType_eq _ hα (Fragment.subset_generated _ (Set.mem_singleton _)) h

def headline : List Name :=
  [`FirstOrder.Language.qrank_openBounds,
   `FirstOrder.Language.Fragment.realizedType_eq_of_bfEquiv,
   `FirstOrder.Language.Fragment.realize_scottBounded_iff,
   `FirstOrder.Language.Fragment.bfEquiv_of_realizedType_eq,
   `adapterA_empty_regression, `adapterB_generated_regression]

def standardAxioms : List Name := [`propext, `Classical.choice, `Quot.sound]

run_cmd do
  let env ← getEnv
  for n in headline do
    unless (env.find? n).isSome do throwError "headline declaration {n} not found"
    let axs ← Elab.Command.liftCoreM (collectAxioms n)
    let bad := axs.toList.filter fun a => !standardAxioms.contains a
    unless bad.isEmpty do throwError "[NONSTANDARD AXIOMS] {n} uses {bad}"
  logInfo "fragment BF-adapter guard: OK (A at level zero on an empty slice; B by membership in \
    a generated fragment; headline declarations on standard axioms)"
