/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import InfinitaryLogic.Conditional.SentenceSpectrum
import InfinitaryLogic.Descriptive.RealizedSpectrum
import Architect

/-!
# Thinness is countability of every fragment spectrum

For a Borel class `C` of coded structures over a countable relational language,

  `IsThinOn (structureIsoSetoid L) C ↔
     ∀ F : Fragment L, F.toSet.Countable → ∀ n, (F.typeSpectrum n C).Countable`

(`thin_iff_countable_fragment_spectra`): `C` carries no perfect set of pairwise non-isomorphic
structures exactly when every countable fragment realizes only countably many `n`-types on `C`,
at every finite arity.  The class need not be isomorphism-invariant.

* Thin ⟹ countable spectra (`fragmentSpectrum_countable_or_cantor`): Silver's dichotomy
  (`silver_countable_or_cantorAntichain`) is applied to spectrum equivalence, the Borel relation
  "same realized `F`-types at arity `n`" (`measurableSet_sameRealizedSpectrum`), which isomorphism
  refines (`sameRealizedSpectrum_of_iso`).  Countably many classes give countably many realized
  spectra, each countable, hence countably many realized types; the Cantor alternative is an
  isomorphism antichain, which thinness excludes.  This is Marker's argument (Corollary 3.3.3);
  no Baire-property theorem for analytic sets enters.
* Countable spectra ⟹ thin: arity zero.  For a sentence list `θ`, the fragment generated by its
  range is countable, and its arity-zero spectrum determines the truth sequences of `θ`; so
  countable fragment spectra give countable sentence spectra, and the sentence-spectrum
  characterization (`thin_iff_countable_sentence_spectra`) finishes.

## Not claimed

The realized spectrum is not a complete isomorphism invariant, and nothing here proves any
particular class thin: the theorem connects the existing criteria.

Classical background: Marker, *Lectures on Infinitary Model Theory* (Cambridge, 2016),
Definition 3.3.1, Corollary 3.3.3, and Corollary 3.3.10.
-/

namespace FirstOrder.Language

open MeasureTheory Set

variable {L : Language.{0, 0}} [L.IsRelational] [Countable (Σ n, L.Relations n)]

namespace Fragment

/-- **Silver on spectrum equivalence.**  For a Borel class and a countable fragment at a fixed
arity, either the realized spectrum on the class is countable or the class contains a
continuous Cantor isomorphism antichain. -/
theorem fragmentSpectrum_countable_or_cantor (F : Fragment L) (hF : F.toSet.Countable) (n : ℕ)
    (C : Set (StructureSpace L)) (hC : MeasurableSet C) :
    (F.typeSpectrum n C).Countable ∨ HasCantorAntichainOn (structureIsoSetoid L) C := by
  let s : Setoid C := Setoid.comap Subtype.val (F.sameRealizedSpectrumSetoid n)
  have hs : MeasurableSet {p : C × C | s.r p.1 p.2} :=
    (measurableSet_sameRealizedSpectrum F n hF).preimage
      (measurable_subtype_coe.prodMap measurable_subtype_coe)
  rcases silver_countable_or_cantorAntichain hC (structureIsoSetoid L) s
      (fun _ _ h => sameRealizedSpectrum_of_iso F n h) hs with hc | ha
  · left
    have hsub : F.typeSpectrum n C ⊆ ⋃ q : Quotient s, F.realizedSpectrum n (Quotient.out q).1 := by
      intro t ht
      obtain ⟨c, hc', a, rfl⟩ := mem_typeSpectrum.mp ht
      refine Set.mem_iUnion.mpr ⟨Quotient.mk s ⟨c, hc'⟩, ?_⟩
      have hq : s.r (Quotient.out (Quotient.mk s ⟨c, hc'⟩)) ⟨c, hc'⟩ :=
        Quotient.exact (Quotient.out_eq _)
      have heq : F.realizedSpectrum n (Quotient.out (Quotient.mk s ⟨c, hc'⟩)).1 =
          F.realizedSpectrum n c := hq
      rw [heq]
      exact ⟨a, rfl⟩
    exact (Set.countable_iUnion fun q => realizedSpectrum_countable F n _).mono hsub
  · exact Or.inr ha

/-- **Thinness is countability of every fragment spectrum**, on any Borel class. -/
@[blueprint "thm:thin-iff-countable-fragment-spectra"
  (title := /-- The fragment-spectrum characterization of thinness -/)
  (statement := /-- Let $C$ be a Borel class of coded structures over a countable relational
    language.  Then $C$ is thin for isomorphism if and only if for every countable fragment $F$
    and every finite arity $n$, only countably many $F$-types of $n$-tuples are realized in
    members of $C$.  The class need not be isomorphism-invariant. -/)
  (proof := /-- Thin to countable: for fixed $F$ and $n$, the relation ``$c$ and $d$ realize
    the same $F$-types of $n$-tuples'' is Borel --- every tuple of one has a matching tuple in
    the other, matching being agreement on the countably many members of the slice --- and it
    is refined by isomorphism.  Silver's dichotomy on $C$ gives either countably many classes,
    each realizing countably many types, or a continuous Cantor antichain for the relation,
    hence for isomorphism, which thinness excludes.  Countable to thin: at arity zero, the
    fragment generated by a sentence list is countable and its spectrum determines the truth
    sequences of the list, so the sentence-spectrum characterization applies. -/)
  (uses := ["thm:thin-iff-countable-sentence-spectra"])]
theorem thin_iff_countable_fragment_spectra (C : Set (StructureSpace L)) (hC : MeasurableSet C) :
    IsThinOn (structureIsoSetoid L) C ↔
      ∀ F : Fragment L, F.toSet.Countable → ∀ n : ℕ, (F.typeSpectrum n C).Countable := by
  constructor
  · intro hthin F hF n
    rcases fragmentSpectrum_countable_or_cantor F hF n C hC with h | h
    · exact h
    · exact (hthin h.hasPerfectAntichainOn).elim
  · intro h
    rw [thin_iff_countable_sentence_spectra C hC]
    intro θ
    have hθ : ∀ k, (⟨0, θ k⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ generatedTheory (Set.range θ) :=
      fun k => mem_generatedTheory ⟨k, rfl⟩
    have hF := h (generatedTheory (Set.range θ))
      (generatedTheory_countable (Set.countable_range θ)) 0
    refine (hF.image fun t : (generatedTheory (Set.range θ)).slice 0 → Bool =>
      fun k => t ⟨θ k, hθ k⟩).mono ?_
    rintro _ ⟨c, hc, rfl⟩
    refine ⟨_, mem_typeSpectrum.mpr ⟨c, hc, Fin.elim0, rfl⟩, ?_⟩
    exact (pointedType_zero_eq_sentenceTheory _ θ hθ c).symm

/-- Sentence form: a sentence is thin on its `ℕ`-models exactly when every countable fragment
realizes only countably many types, at every arity, in its models. -/
theorem _root_.FirstOrder.Language.Sentenceω.isThinOnNatModels_iff_countable_fragment_spectra
    (φ : L.Sentenceω) :
    φ.IsThinOnNatModels ↔
      ∀ F : Fragment L, F.toSet.Countable → ∀ n : ℕ, (F.typeSpectrum n (ModelsOf φ)).Countable :=
  thin_iff_countable_fragment_spectra (ModelsOf φ) (modelsOf_measurableSet φ)

end Fragment

end FirstOrder.Language
